//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIntegracao
    {
        public int Id { get; set; }
        public string Projeto { get; set; }
        public System.DateTime Data { get; set; }
        public string Registro { get; set; }
        public bool Status { get; set; }
    }
}
