//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Projeto> ProjetoSet { get; set; }
        public virtual DbSet<UsuarioVpn> UsuarioVpnSet { get; set; }
        public virtual DbSet<VpnHistorico> VpnHistoricoSet { get; set; }
        public virtual DbSet<TarefaChannel> TarefaChannelSet { get; set; }
        public virtual DbSet<Usuario> UsuarioSet { get; set; }
        public virtual DbSet<Perfil> PerfilSet { get; set; }
        public virtual DbSet<LogIntegracao> LogIntegracaoSet { get; set; }
        public virtual DbSet<ParametroSistema> ParametroSistemaSet { get; set; }
    }
}
