//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projeto()
        {
            this.TarefaChannel = new HashSet<TarefaChannel>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string TfsUrl { get; set; }
        public string TfsCollection { get; set; }
        public string TfsProject { get; set; }
        public string TfsTeam { get; set; }
        public int IdChannel { get; set; }
        public bool Status { get; set; }
        public string TfsAreaPath { get; set; }
        public string UsuarioGerente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaChannel> TarefaChannel { get; set; }
    }
}
