//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioVpn
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fim { get; set; }
        public string Nome { get; set; }
    }
}
