//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VpnHistorico
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Fim { get; set; }
        public System.DateTime DataAcao { get; set; }
        public int Acao { get; set; }
        public string Responsavel { get; set; }
        public string Usuario { get; set; }
        public string Justificativa { get; set; }
    }
}
