//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Business.ChannelOperacaoWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", ConfigurationName="ChannelOperacaoWebService.ChannelOperacaoWebServicePortType")]
    public interface ChannelOperacaoWebServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:atualizarPassoSolicitacao", ReplyAction="urn:atualizarPassoSolicitacaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoResponse atualizarPassoSolicitacao(Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:atualizarPassoSolicitacao", ReplyAction="urn:atualizarPassoSolicitacaoResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoResponse> atualizarPassoSolicitacaoAsync(Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:consultarDemanda", ReplyAction="urn:consultarDemandaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelOperacaoWebService.consultarDemandaResponse consultarDemanda(Xerife.Business.ChannelOperacaoWebService.consultarDemandaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:consultarDemanda", ReplyAction="urn:consultarDemandaResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.consultarDemandaResponse> consultarDemandaAsync(Xerife.Business.ChannelOperacaoWebService.consultarDemandaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:atualizarPassoSolicitacaoPorIdPasso", ReplyAction="urn:atualizarPassoSolicitacaoPorIdPassoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoResponse atualizarPassoSolicitacaoPorIdPasso(Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:atualizarPassoSolicitacaoPorIdPasso", ReplyAction="urn:atualizarPassoSolicitacaoPorIdPassoResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoResponse> atualizarPassoSolicitacaoPorIdPassoAsync(Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarProjetosAtivos", ReplyAction="urn:listarProjetosAtivosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosResponse listarProjetosAtivos(Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarProjetosAtivos", ReplyAction="urn:listarProjetosAtivosResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosResponse> listarProjetosAtivosAsync(Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarSolicitacoesPorOperacao", ReplyAction="urn:listarSolicitacoesPorOperacaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoResponse listarSolicitacoesPorOperacao(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarSolicitacoesPorOperacao", ReplyAction="urn:listarSolicitacoesPorOperacaoResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoResponse> listarSolicitacoesPorOperacaoAsync(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarSolicitacoesOperacaoTicket", ReplyAction="urn:listarSolicitacoesOperacaoTicketResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketResponse listarSolicitacoesOperacaoTicket(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarSolicitacoesOperacaoTicket", ReplyAction="urn:listarSolicitacoesOperacaoTicketResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketResponse> listarSolicitacoesOperacaoTicketAsync(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarSolicitacoes", ReplyAction="urn:listarSolicitacoesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesResponse listarSolicitacoes(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarSolicitacoes", ReplyAction="urn:listarSolicitacoesResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesResponse> listarSolicitacoesAsync(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generics.channel2.jexperts.com.br/xsd")]
    public partial class ResultadoOperacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private System.Nullable<int> idEmpresaField;
        
        private bool idEmpresaFieldSpecified;
        
        private object logField;
        
        private string mensagemField;
        
        private object objectField;
        
        private bool realizadaField;
        
        private bool realizadaFieldSpecified;
        
        private string tipoMensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                this.idEmpresaField = value;
                this.RaisePropertyChanged("idEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEmpresaSpecified {
            get {
                return this.idEmpresaFieldSpecified;
            }
            set {
                this.idEmpresaFieldSpecified = value;
                this.RaisePropertyChanged("idEmpresaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public object log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("log");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public object @object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
                this.RaisePropertyChanged("object");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool realizada {
            get {
                return this.realizadaField;
            }
            set {
                this.realizadaField = value;
                this.RaisePropertyChanged("realizada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool realizadaSpecified {
            get {
                return this.realizadaFieldSpecified;
            }
            set {
                this.realizadaFieldSpecified = value;
                this.RaisePropertyChanged("realizadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string tipoMensagem {
            get {
                return this.tipoMensagemField;
            }
            set {
                this.tipoMensagemField = value;
                this.RaisePropertyChanged("tipoMensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class SolicitacaoOperacaoDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campoParticipacaoEquipeTestesField;
        
        private string codigoField;
        
        private string conteudoContaControleField;
        
        private string conteudoCronogramaDeTestesField;
        
        private string conteudoPlanoDeTestesField;
        
        private string dataAberturaField;
        
        private string dataFimField;
        
        private string dataTestePlanejadoFimField;
        
        private string dataTestePlanejadoInicioField;
        
        private string dataTesteRealizadoFimField;
        
        private string dataTesteRealizadoInicioField;
        
        private string operacaoField;
        
        private string passoAtualField;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string campoParticipacaoEquipeTestes {
            get {
                return this.campoParticipacaoEquipeTestesField;
            }
            set {
                this.campoParticipacaoEquipeTestesField = value;
                this.RaisePropertyChanged("campoParticipacaoEquipeTestes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string conteudoContaControle {
            get {
                return this.conteudoContaControleField;
            }
            set {
                this.conteudoContaControleField = value;
                this.RaisePropertyChanged("conteudoContaControle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string conteudoCronogramaDeTestes {
            get {
                return this.conteudoCronogramaDeTestesField;
            }
            set {
                this.conteudoCronogramaDeTestesField = value;
                this.RaisePropertyChanged("conteudoCronogramaDeTestes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string conteudoPlanoDeTestes {
            get {
                return this.conteudoPlanoDeTestesField;
            }
            set {
                this.conteudoPlanoDeTestesField = value;
                this.RaisePropertyChanged("conteudoPlanoDeTestes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string dataAbertura {
            get {
                return this.dataAberturaField;
            }
            set {
                this.dataAberturaField = value;
                this.RaisePropertyChanged("dataAbertura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string dataFim {
            get {
                return this.dataFimField;
            }
            set {
                this.dataFimField = value;
                this.RaisePropertyChanged("dataFim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string dataTestePlanejadoFim {
            get {
                return this.dataTestePlanejadoFimField;
            }
            set {
                this.dataTestePlanejadoFimField = value;
                this.RaisePropertyChanged("dataTestePlanejadoFim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string dataTestePlanejadoInicio {
            get {
                return this.dataTestePlanejadoInicioField;
            }
            set {
                this.dataTestePlanejadoInicioField = value;
                this.RaisePropertyChanged("dataTestePlanejadoInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string dataTesteRealizadoFim {
            get {
                return this.dataTesteRealizadoFimField;
            }
            set {
                this.dataTesteRealizadoFimField = value;
                this.RaisePropertyChanged("dataTesteRealizadoFim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string dataTesteRealizadoInicio {
            get {
                return this.dataTesteRealizadoInicioField;
            }
            set {
                this.dataTesteRealizadoInicioField = value;
                this.RaisePropertyChanged("dataTesteRealizadoInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string operacao {
            get {
                return this.operacaoField;
            }
            set {
                this.operacaoField = value;
                this.RaisePropertyChanged("operacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string passoAtual {
            get {
                return this.passoAtualField;
            }
            set {
                this.passoAtualField = value;
                this.RaisePropertyChanged("passoAtual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class DadosSolicitacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private System.Nullable<int> idOperacaoField;
        
        private bool idOperacaoFieldSpecified;
        
        private System.Nullable<int> idTipoTicketField;
        
        private bool idTipoTicketFieldSpecified;
        
        private string nomeField;
        
        private string nomeOperacaoField;
        
        private string passoWorkflowField;
        
        private string responsavelField;
        
        private string tipoTicketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> idOperacao {
            get {
                return this.idOperacaoField;
            }
            set {
                this.idOperacaoField = value;
                this.RaisePropertyChanged("idOperacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idOperacaoSpecified {
            get {
                return this.idOperacaoFieldSpecified;
            }
            set {
                this.idOperacaoFieldSpecified = value;
                this.RaisePropertyChanged("idOperacaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> idTipoTicket {
            get {
                return this.idTipoTicketField;
            }
            set {
                this.idTipoTicketField = value;
                this.RaisePropertyChanged("idTipoTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoTicketSpecified {
            get {
                return this.idTipoTicketFieldSpecified;
            }
            set {
                this.idTipoTicketFieldSpecified = value;
                this.RaisePropertyChanged("idTipoTicketSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string nomeOperacao {
            get {
                return this.nomeOperacaoField;
            }
            set {
                this.nomeOperacaoField = value;
                this.RaisePropertyChanged("nomeOperacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string passoWorkflow {
            get {
                return this.passoWorkflowField;
            }
            set {
                this.passoWorkflowField = value;
                this.RaisePropertyChanged("passoWorkflow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string responsavel {
            get {
                return this.responsavelField;
            }
            set {
                this.responsavelField = value;
                this.RaisePropertyChanged("responsavel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string tipoTicket {
            get {
                return this.tipoTicketField;
            }
            set {
                this.tipoTicketField = value;
                this.RaisePropertyChanged("tipoTicket");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class DadosProjeto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> idProjetoField;
        
        private bool idProjetoFieldSpecified;
        
        private string nomeGerenteField;
        
        private string nomeProjetoField;
        
        private string usernameGerenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> idProjeto {
            get {
                return this.idProjetoField;
            }
            set {
                this.idProjetoField = value;
                this.RaisePropertyChanged("idProjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProjetoSpecified {
            get {
                return this.idProjetoFieldSpecified;
            }
            set {
                this.idProjetoFieldSpecified = value;
                this.RaisePropertyChanged("idProjetoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string nomeGerente {
            get {
                return this.nomeGerenteField;
            }
            set {
                this.nomeGerenteField = value;
                this.RaisePropertyChanged("nomeGerente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string nomeProjeto {
            get {
                return this.nomeProjetoField;
            }
            set {
                this.nomeProjetoField = value;
                this.RaisePropertyChanged("nomeProjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string usernameGerente {
            get {
                return this.usernameGerenteField;
            }
            set {
                this.usernameGerenteField = value;
                this.RaisePropertyChanged("usernameGerente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class DadosDemanda : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string autorDemandaField;
        
        private string codigoDemandaField;
        
        private System.Nullable<int> codigoStatusDemandaField;
        
        private bool codigoStatusDemandaFieldSpecified;
        
        private System.Nullable<System.DateTime> dataAberturaDemandaField;
        
        private bool dataAberturaDemandaFieldSpecified;
        
        private System.Nullable<System.DateTime> dataUltimaAtualizacaoDemandaField;
        
        private bool dataUltimaAtualizacaoDemandaFieldSpecified;
        
        private string descricaoDemandaField;
        
        private string nomeDemandaField;
        
        private string nomeStatusDemandaField;
        
        private string responsavelDemandaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string autorDemanda {
            get {
                return this.autorDemandaField;
            }
            set {
                this.autorDemandaField = value;
                this.RaisePropertyChanged("autorDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codigoDemanda {
            get {
                return this.codigoDemandaField;
            }
            set {
                this.codigoDemandaField = value;
                this.RaisePropertyChanged("codigoDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> codigoStatusDemanda {
            get {
                return this.codigoStatusDemandaField;
            }
            set {
                this.codigoStatusDemandaField = value;
                this.RaisePropertyChanged("codigoStatusDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codigoStatusDemandaSpecified {
            get {
                return this.codigoStatusDemandaFieldSpecified;
            }
            set {
                this.codigoStatusDemandaFieldSpecified = value;
                this.RaisePropertyChanged("codigoStatusDemandaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> dataAberturaDemanda {
            get {
                return this.dataAberturaDemandaField;
            }
            set {
                this.dataAberturaDemandaField = value;
                this.RaisePropertyChanged("dataAberturaDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataAberturaDemandaSpecified {
            get {
                return this.dataAberturaDemandaFieldSpecified;
            }
            set {
                this.dataAberturaDemandaFieldSpecified = value;
                this.RaisePropertyChanged("dataAberturaDemandaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> dataUltimaAtualizacaoDemanda {
            get {
                return this.dataUltimaAtualizacaoDemandaField;
            }
            set {
                this.dataUltimaAtualizacaoDemandaField = value;
                this.RaisePropertyChanged("dataUltimaAtualizacaoDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataUltimaAtualizacaoDemandaSpecified {
            get {
                return this.dataUltimaAtualizacaoDemandaFieldSpecified;
            }
            set {
                this.dataUltimaAtualizacaoDemandaFieldSpecified = value;
                this.RaisePropertyChanged("dataUltimaAtualizacaoDemandaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string descricaoDemanda {
            get {
                return this.descricaoDemandaField;
            }
            set {
                this.descricaoDemandaField = value;
                this.RaisePropertyChanged("descricaoDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string nomeDemanda {
            get {
                return this.nomeDemandaField;
            }
            set {
                this.nomeDemandaField = value;
                this.RaisePropertyChanged("nomeDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string nomeStatusDemanda {
            get {
                return this.nomeStatusDemandaField;
            }
            set {
                this.nomeStatusDemandaField = value;
                this.RaisePropertyChanged("nomeStatusDemanda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string responsavelDemanda {
            get {
                return this.responsavelDemandaField;
            }
            set {
                this.responsavelDemandaField = value;
                this.RaisePropertyChanged("responsavelDemanda");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="atualizarPassoSolicitacao", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class atualizarPassoSolicitacaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        public int idSolicitacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nomeNovoPasso;
        
        public atualizarPassoSolicitacaoRequest() {
        }
        
        public atualizarPassoSolicitacaoRequest(int idSolicitacao, string nomeNovoPasso) {
            this.idSolicitacao = idSolicitacao;
            this.nomeNovoPasso = nomeNovoPasso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="atualizarPassoSolicitacaoResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class atualizarPassoSolicitacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Xerife.Business.ChannelOperacaoWebService.ResultadoOperacao @return;
        
        public atualizarPassoSolicitacaoResponse() {
        }
        
        public atualizarPassoSolicitacaoResponse(Xerife.Business.ChannelOperacaoWebService.ResultadoOperacao @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDemanda", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class consultarDemandaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codigoDemanda;
        
        public consultarDemandaRequest() {
        }
        
        public consultarDemandaRequest(string codigoDemanda) {
            this.codigoDemanda = codigoDemanda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarDemandaResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class consultarDemandaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Xerife.Business.ChannelOperacaoWebService.DadosDemanda @return;
        
        public consultarDemandaResponse() {
        }
        
        public consultarDemandaResponse(Xerife.Business.ChannelOperacaoWebService.DadosDemanda @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="atualizarPassoSolicitacaoPorIdPasso", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class atualizarPassoSolicitacaoPorIdPassoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        public int idSolicitacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        public int idNovoPasso;
        
        public atualizarPassoSolicitacaoPorIdPassoRequest() {
        }
        
        public atualizarPassoSolicitacaoPorIdPassoRequest(int idSolicitacao, int idNovoPasso) {
            this.idSolicitacao = idSolicitacao;
            this.idNovoPasso = idNovoPasso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="atualizarPassoSolicitacaoPorIdPassoResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class atualizarPassoSolicitacaoPorIdPassoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Xerife.Business.ChannelOperacaoWebService.ResultadoOperacao @return;
        
        public atualizarPassoSolicitacaoPorIdPassoResponse() {
        }
        
        public atualizarPassoSolicitacaoPorIdPassoResponse(Xerife.Business.ChannelOperacaoWebService.ResultadoOperacao @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProjetosAtivos", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarProjetosAtivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string login;
        
        public listarProjetosAtivosRequest() {
        }
        
        public listarProjetosAtivosRequest(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProjetosAtivosResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarProjetosAtivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Xerife.Business.ChannelOperacaoWebService.DadosProjeto[] @return;
        
        public listarProjetosAtivosResponse() {
        }
        
        public listarProjetosAtivosResponse(Xerife.Business.ChannelOperacaoWebService.DadosProjeto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSolicitacoesPorOperacao", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarSolicitacoesPorOperacaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        public int idOperacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        public int idTipoSolicitacao;
        
        public listarSolicitacoesPorOperacaoRequest() {
        }
        
        public listarSolicitacoesPorOperacaoRequest(int idOperacao, int idTipoSolicitacao) {
            this.idOperacao = idOperacao;
            this.idTipoSolicitacao = idTipoSolicitacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSolicitacoesPorOperacaoResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarSolicitacoesPorOperacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Xerife.Business.ChannelOperacaoWebService.DadosSolicitacao[] @return;
        
        public listarSolicitacoesPorOperacaoResponse() {
        }
        
        public listarSolicitacoesPorOperacaoResponse(Xerife.Business.ChannelOperacaoWebService.DadosSolicitacao[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSolicitacoesOperacaoTicket", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarSolicitacoesOperacaoTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataFim;
        
        public listarSolicitacoesOperacaoTicketRequest() {
        }
        
        public listarSolicitacoesOperacaoTicketRequest(string dataInicio, string dataFim) {
            this.dataInicio = dataInicio;
            this.dataFim = dataFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSolicitacoesOperacaoTicketResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarSolicitacoesOperacaoTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Xerife.Business.ChannelOperacaoWebService.SolicitacaoOperacaoDTO[] @return;
        
        public listarSolicitacoesOperacaoTicketResponse() {
        }
        
        public listarSolicitacoesOperacaoTicketResponse(Xerife.Business.ChannelOperacaoWebService.SolicitacaoOperacaoDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSolicitacoes", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarSolicitacoesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        public int idProjeto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nomeTipoSolicitacao;
        
        public listarSolicitacoesRequest() {
        }
        
        public listarSolicitacoesRequest(int idProjeto, string nomeTipoSolicitacao) {
            this.idProjeto = idProjeto;
            this.nomeTipoSolicitacao = nomeTipoSolicitacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSolicitacoesResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarSolicitacoesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Xerife.Business.ChannelOperacaoWebService.DadosSolicitacao[] @return;
        
        public listarSolicitacoesResponse() {
        }
        
        public listarSolicitacoesResponse(Xerife.Business.ChannelOperacaoWebService.DadosSolicitacao[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChannelOperacaoWebServicePortTypeChannel : Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelOperacaoWebServicePortTypeClient : System.ServiceModel.ClientBase<Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType>, Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType {
        
        public ChannelOperacaoWebServicePortTypeClient() {
        }
        
        public ChannelOperacaoWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelOperacaoWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelOperacaoWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelOperacaoWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoResponse Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.atualizarPassoSolicitacao(Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoRequest request) {
            return base.Channel.atualizarPassoSolicitacao(request);
        }
        
        public Xerife.Business.ChannelOperacaoWebService.ResultadoOperacao atualizarPassoSolicitacao(int idSolicitacao, string nomeNovoPasso) {
            Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoRequest inValue = new Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoRequest();
            inValue.idSolicitacao = idSolicitacao;
            inValue.nomeNovoPasso = nomeNovoPasso;
            Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoResponse retVal = ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).atualizarPassoSolicitacao(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoResponse> Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.atualizarPassoSolicitacaoAsync(Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoRequest request) {
            return base.Channel.atualizarPassoSolicitacaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoResponse> atualizarPassoSolicitacaoAsync(int idSolicitacao, string nomeNovoPasso) {
            Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoRequest inValue = new Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoRequest();
            inValue.idSolicitacao = idSolicitacao;
            inValue.nomeNovoPasso = nomeNovoPasso;
            return ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).atualizarPassoSolicitacaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelOperacaoWebService.consultarDemandaResponse Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.consultarDemanda(Xerife.Business.ChannelOperacaoWebService.consultarDemandaRequest request) {
            return base.Channel.consultarDemanda(request);
        }
        
        public Xerife.Business.ChannelOperacaoWebService.DadosDemanda consultarDemanda(string codigoDemanda) {
            Xerife.Business.ChannelOperacaoWebService.consultarDemandaRequest inValue = new Xerife.Business.ChannelOperacaoWebService.consultarDemandaRequest();
            inValue.codigoDemanda = codigoDemanda;
            Xerife.Business.ChannelOperacaoWebService.consultarDemandaResponse retVal = ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).consultarDemanda(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.consultarDemandaResponse> Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.consultarDemandaAsync(Xerife.Business.ChannelOperacaoWebService.consultarDemandaRequest request) {
            return base.Channel.consultarDemandaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.consultarDemandaResponse> consultarDemandaAsync(string codigoDemanda) {
            Xerife.Business.ChannelOperacaoWebService.consultarDemandaRequest inValue = new Xerife.Business.ChannelOperacaoWebService.consultarDemandaRequest();
            inValue.codigoDemanda = codigoDemanda;
            return ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).consultarDemandaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoResponse Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.atualizarPassoSolicitacaoPorIdPasso(Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoRequest request) {
            return base.Channel.atualizarPassoSolicitacaoPorIdPasso(request);
        }
        
        public Xerife.Business.ChannelOperacaoWebService.ResultadoOperacao atualizarPassoSolicitacaoPorIdPasso(int idSolicitacao, int idNovoPasso) {
            Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoRequest inValue = new Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoRequest();
            inValue.idSolicitacao = idSolicitacao;
            inValue.idNovoPasso = idNovoPasso;
            Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoResponse retVal = ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).atualizarPassoSolicitacaoPorIdPasso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoResponse> Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.atualizarPassoSolicitacaoPorIdPassoAsync(Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoRequest request) {
            return base.Channel.atualizarPassoSolicitacaoPorIdPassoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoResponse> atualizarPassoSolicitacaoPorIdPassoAsync(int idSolicitacao, int idNovoPasso) {
            Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoRequest inValue = new Xerife.Business.ChannelOperacaoWebService.atualizarPassoSolicitacaoPorIdPassoRequest();
            inValue.idSolicitacao = idSolicitacao;
            inValue.idNovoPasso = idNovoPasso;
            return ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).atualizarPassoSolicitacaoPorIdPassoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosResponse Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.listarProjetosAtivos(Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosRequest request) {
            return base.Channel.listarProjetosAtivos(request);
        }
        
        public Xerife.Business.ChannelOperacaoWebService.DadosProjeto[] listarProjetosAtivos(string login) {
            Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosRequest inValue = new Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosRequest();
            inValue.login = login;
            Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosResponse retVal = ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).listarProjetosAtivos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosResponse> Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.listarProjetosAtivosAsync(Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosRequest request) {
            return base.Channel.listarProjetosAtivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosResponse> listarProjetosAtivosAsync(string login) {
            Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosRequest inValue = new Xerife.Business.ChannelOperacaoWebService.listarProjetosAtivosRequest();
            inValue.login = login;
            return ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).listarProjetosAtivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoResponse Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.listarSolicitacoesPorOperacao(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoRequest request) {
            return base.Channel.listarSolicitacoesPorOperacao(request);
        }
        
        public Xerife.Business.ChannelOperacaoWebService.DadosSolicitacao[] listarSolicitacoesPorOperacao(int idOperacao, int idTipoSolicitacao) {
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoRequest inValue = new Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoRequest();
            inValue.idOperacao = idOperacao;
            inValue.idTipoSolicitacao = idTipoSolicitacao;
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoResponse retVal = ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).listarSolicitacoesPorOperacao(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoResponse> Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.listarSolicitacoesPorOperacaoAsync(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoRequest request) {
            return base.Channel.listarSolicitacoesPorOperacaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoResponse> listarSolicitacoesPorOperacaoAsync(int idOperacao, int idTipoSolicitacao) {
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoRequest inValue = new Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesPorOperacaoRequest();
            inValue.idOperacao = idOperacao;
            inValue.idTipoSolicitacao = idTipoSolicitacao;
            return ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).listarSolicitacoesPorOperacaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketResponse Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.listarSolicitacoesOperacaoTicket(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketRequest request) {
            return base.Channel.listarSolicitacoesOperacaoTicket(request);
        }
        
        public Xerife.Business.ChannelOperacaoWebService.SolicitacaoOperacaoDTO[] listarSolicitacoesOperacaoTicket(string dataInicio, string dataFim) {
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketRequest inValue = new Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketRequest();
            inValue.dataInicio = dataInicio;
            inValue.dataFim = dataFim;
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketResponse retVal = ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).listarSolicitacoesOperacaoTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketResponse> Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.listarSolicitacoesOperacaoTicketAsync(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketRequest request) {
            return base.Channel.listarSolicitacoesOperacaoTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketResponse> listarSolicitacoesOperacaoTicketAsync(string dataInicio, string dataFim) {
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketRequest inValue = new Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesOperacaoTicketRequest();
            inValue.dataInicio = dataInicio;
            inValue.dataFim = dataFim;
            return ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).listarSolicitacoesOperacaoTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesResponse Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.listarSolicitacoes(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesRequest request) {
            return base.Channel.listarSolicitacoes(request);
        }
        
        public Xerife.Business.ChannelOperacaoWebService.DadosSolicitacao[] listarSolicitacoes(int idProjeto, string nomeTipoSolicitacao) {
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesRequest inValue = new Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesRequest();
            inValue.idProjeto = idProjeto;
            inValue.nomeTipoSolicitacao = nomeTipoSolicitacao;
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesResponse retVal = ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).listarSolicitacoes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesResponse> Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType.listarSolicitacoesAsync(Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesRequest request) {
            return base.Channel.listarSolicitacoesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesResponse> listarSolicitacoesAsync(int idProjeto, string nomeTipoSolicitacao) {
            Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesRequest inValue = new Xerife.Business.ChannelOperacaoWebService.listarSolicitacoesRequest();
            inValue.idProjeto = idProjeto;
            inValue.nomeTipoSolicitacao = nomeTipoSolicitacao;
            return ((Xerife.Business.ChannelOperacaoWebService.ChannelOperacaoWebServicePortType)(this)).listarSolicitacoesAsync(inValue);
        }
    }
}
