//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Web.ChannelProjetoWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", ConfigurationName="ChannelProjetoWebService.ChannelProjetoWebServicePortType")]
    public interface ChannelProjetoWebServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarQuestoesPendentes", ReplyAction="urn:listarQuestoesPendentesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesResponse listarQuestoesPendentes(Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarQuestoesPendentes", ReplyAction="urn:listarQuestoesPendentesResponse")]
        System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesResponse> listarQuestoesPendentesAsync(Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarAtividadesProjetos", ReplyAction="urn:listarAtividadesProjetosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosResponse listarAtividadesProjetos(Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarAtividadesProjetos", ReplyAction="urn:listarAtividadesProjetosResponse")]
        System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosResponse> listarAtividadesProjetosAsync(Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarRiscosProjetos", ReplyAction="urn:listarRiscosProjetosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosResponse listarRiscosProjetos(Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listarRiscosProjetos", ReplyAction="urn:listarRiscosProjetosResponse")]
        System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosResponse> listarRiscosProjetosAsync(Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class DadosQuestaoPendente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> dataLimiteField;
        
        private bool dataLimiteFieldSpecified;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nomeField;
        
        private string responsavelField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> dataLimite {
            get {
                return this.dataLimiteField;
            }
            set {
                this.dataLimiteField = value;
                this.RaisePropertyChanged("dataLimite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataLimiteSpecified {
            get {
                return this.dataLimiteFieldSpecified;
            }
            set {
                this.dataLimiteFieldSpecified = value;
                this.RaisePropertyChanged("dataLimiteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string responsavel {
            get {
                return this.responsavelField;
            }
            set {
                this.responsavelField = value;
                this.RaisePropertyChanged("responsavel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class DadosRisco : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> dataFimField;
        
        private bool dataFimFieldSpecified;
        
        private System.Nullable<System.DateTime> dataInicioField;
        
        private bool dataInicioFieldSpecified;
        
        private string estrategiaRespostaField;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nomeField;
        
        private string responsavelField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> dataFim {
            get {
                return this.dataFimField;
            }
            set {
                this.dataFimField = value;
                this.RaisePropertyChanged("dataFim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataFimSpecified {
            get {
                return this.dataFimFieldSpecified;
            }
            set {
                this.dataFimFieldSpecified = value;
                this.RaisePropertyChanged("dataFimSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> dataInicio {
            get {
                return this.dataInicioField;
            }
            set {
                this.dataInicioField = value;
                this.RaisePropertyChanged("dataInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataInicioSpecified {
            get {
                return this.dataInicioFieldSpecified;
            }
            set {
                this.dataInicioFieldSpecified = value;
                this.RaisePropertyChanged("dataInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string estrategiaResposta {
            get {
                return this.estrategiaRespostaField;
            }
            set {
                this.estrategiaRespostaField = value;
                this.RaisePropertyChanged("estrategiaResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string responsavel {
            get {
                return this.responsavelField;
            }
            set {
                this.responsavelField = value;
                this.RaisePropertyChanged("responsavel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class DadosAtividade : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> dataFimField;
        
        private bool dataFimFieldSpecified;
        
        private System.Nullable<System.DateTime> dataInicioField;
        
        private bool dataInicioFieldSpecified;
        
        private string edtField;
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string nomeField;
        
        private System.Nullable<double> percentualConcluidoField;
        
        private bool percentualConcluidoFieldSpecified;
        
        private string responsavelField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> dataFim {
            get {
                return this.dataFimField;
            }
            set {
                this.dataFimField = value;
                this.RaisePropertyChanged("dataFim");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataFimSpecified {
            get {
                return this.dataFimFieldSpecified;
            }
            set {
                this.dataFimFieldSpecified = value;
                this.RaisePropertyChanged("dataFimSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> dataInicio {
            get {
                return this.dataInicioField;
            }
            set {
                this.dataInicioField = value;
                this.RaisePropertyChanged("dataInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataInicioSpecified {
            get {
                return this.dataInicioFieldSpecified;
            }
            set {
                this.dataInicioFieldSpecified = value;
                this.RaisePropertyChanged("dataInicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string edt {
            get {
                return this.edtField;
            }
            set {
                this.edtField = value;
                this.RaisePropertyChanged("edt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<double> percentualConcluido {
            get {
                return this.percentualConcluidoField;
            }
            set {
                this.percentualConcluidoField = value;
                this.RaisePropertyChanged("percentualConcluido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool percentualConcluidoSpecified {
            get {
                return this.percentualConcluidoFieldSpecified;
            }
            set {
                this.percentualConcluidoFieldSpecified = value;
                this.RaisePropertyChanged("percentualConcluidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string responsavel {
            get {
                return this.responsavelField;
            }
            set {
                this.responsavelField = value;
                this.RaisePropertyChanged("responsavel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarQuestoesPendentes", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarQuestoesPendentesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        public int idProjeto;
        
        public listarQuestoesPendentesRequest() {
        }
        
        public listarQuestoesPendentesRequest(int idProjeto) {
            this.idProjeto = idProjeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarQuestoesPendentesResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarQuestoesPendentesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Xerife.Web.ChannelProjetoWebService.DadosQuestaoPendente[] @return;
        
        public listarQuestoesPendentesResponse() {
        }
        
        public listarQuestoesPendentesResponse(Xerife.Web.ChannelProjetoWebService.DadosQuestaoPendente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAtividadesProjetos", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarAtividadesProjetosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        public int idProjeto;
        
        public listarAtividadesProjetosRequest() {
        }
        
        public listarAtividadesProjetosRequest(int idProjeto) {
            this.idProjeto = idProjeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAtividadesProjetosResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarAtividadesProjetosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Xerife.Web.ChannelProjetoWebService.DadosAtividade[] @return;
        
        public listarAtividadesProjetosResponse() {
        }
        
        public listarAtividadesProjetosResponse(Xerife.Web.ChannelProjetoWebService.DadosAtividade[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRiscosProjetos", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarRiscosProjetosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        public int idProjeto;
        
        public listarRiscosProjetosRequest() {
        }
        
        public listarRiscosProjetosRequest(int idProjeto) {
            this.idProjeto = idProjeto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRiscosProjetosResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listarRiscosProjetosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Xerife.Web.ChannelProjetoWebService.DadosRisco[] @return;
        
        public listarRiscosProjetosResponse() {
        }
        
        public listarRiscosProjetosResponse(Xerife.Web.ChannelProjetoWebService.DadosRisco[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChannelProjetoWebServicePortTypeChannel : Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelProjetoWebServicePortTypeClient : System.ServiceModel.ClientBase<Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType>, Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType {
        
        public ChannelProjetoWebServicePortTypeClient() {
        }
        
        public ChannelProjetoWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelProjetoWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelProjetoWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelProjetoWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesResponse Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType.listarQuestoesPendentes(Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesRequest request) {
            return base.Channel.listarQuestoesPendentes(request);
        }
        
        public Xerife.Web.ChannelProjetoWebService.DadosQuestaoPendente[] listarQuestoesPendentes(int idProjeto) {
            Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesRequest inValue = new Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesRequest();
            inValue.idProjeto = idProjeto;
            Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesResponse retVal = ((Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType)(this)).listarQuestoesPendentes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesResponse> Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType.listarQuestoesPendentesAsync(Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesRequest request) {
            return base.Channel.listarQuestoesPendentesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesResponse> listarQuestoesPendentesAsync(int idProjeto) {
            Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesRequest inValue = new Xerife.Web.ChannelProjetoWebService.listarQuestoesPendentesRequest();
            inValue.idProjeto = idProjeto;
            return ((Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType)(this)).listarQuestoesPendentesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosResponse Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType.listarAtividadesProjetos(Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosRequest request) {
            return base.Channel.listarAtividadesProjetos(request);
        }
        
        public Xerife.Web.ChannelProjetoWebService.DadosAtividade[] listarAtividadesProjetos(int idProjeto) {
            Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosRequest inValue = new Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosRequest();
            inValue.idProjeto = idProjeto;
            Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosResponse retVal = ((Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType)(this)).listarAtividadesProjetos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosResponse> Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType.listarAtividadesProjetosAsync(Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosRequest request) {
            return base.Channel.listarAtividadesProjetosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosResponse> listarAtividadesProjetosAsync(int idProjeto) {
            Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosRequest inValue = new Xerife.Web.ChannelProjetoWebService.listarAtividadesProjetosRequest();
            inValue.idProjeto = idProjeto;
            return ((Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType)(this)).listarAtividadesProjetosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosResponse Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType.listarRiscosProjetos(Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosRequest request) {
            return base.Channel.listarRiscosProjetos(request);
        }
        
        public Xerife.Web.ChannelProjetoWebService.DadosRisco[] listarRiscosProjetos(int idProjeto) {
            Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosRequest inValue = new Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosRequest();
            inValue.idProjeto = idProjeto;
            Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosResponse retVal = ((Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType)(this)).listarRiscosProjetos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosResponse> Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType.listarRiscosProjetosAsync(Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosRequest request) {
            return base.Channel.listarRiscosProjetosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosResponse> listarRiscosProjetosAsync(int idProjeto) {
            Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosRequest inValue = new Xerife.Web.ChannelProjetoWebService.listarRiscosProjetosRequest();
            inValue.idProjeto = idProjeto;
            return ((Xerife.Web.ChannelProjetoWebService.ChannelProjetoWebServicePortType)(this)).listarRiscosProjetosAsync(inValue);
        }
    }
}
