//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Business.ChannelApontamentoWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", ConfigurationName="ChannelApontamentoWebService.ChannelApontamentoWebServicePortType")]
    public interface ChannelApontamentoWebServicePortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:listaApontamentosPendentes", ReplyAction="urn:listaApontamentosPendentesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesResponse listaApontamentosPendentes(Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:listaApontamentosPendentes", ReplyAction="urn:listaApontamentosPendentesResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesResponse> listaApontamentosPendentesAsync(Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:registrarApontamentoOperacao", ReplyAction="urn:registrarApontamentoOperacaoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoResponse registrarApontamentoOperacao(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:registrarApontamentoOperacao", ReplyAction="urn:registrarApontamentoOperacaoResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoResponse> registrarApontamentoOperacaoAsync(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:registrarApontamento", ReplyAction="urn:registrarApontamentoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelApontamentoWebService.registrarApontamentoResponse registrarApontamento(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:registrarApontamento", ReplyAction="urn:registrarApontamentoResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoResponse> registrarApontamentoAsync(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:registrarApontamentoAvulso", ReplyAction="urn:registrarApontamentoAvulsoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoResponse registrarApontamentoAvulso(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:registrarApontamentoAvulso", ReplyAction="urn:registrarApontamentoAvulsoResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoResponse> registrarApontamentoAvulsoAsync(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:processeApontamentosRealizados", ReplyAction="urn:processeApontamentosRealizadosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosResponse processeApontamentosRealizados(Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:processeApontamentosRealizados", ReplyAction="urn:processeApontamentosRealizadosResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosResponse> processeApontamentosRealizadosAsync(Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:registrarApontamentoProjeto", ReplyAction="urn:registrarApontamentoProjetoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoResponse registrarApontamentoProjeto(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:registrarApontamentoProjeto", ReplyAction="urn:registrarApontamentoProjetoResponse")]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoResponse> registrarApontamentoProjetoAsync(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class ApontamentoPendente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoProjetoField;
        
        private string dataApontamentoField;
        
        private string descricaoAtividadeField;
        
        private string descricaoProgramaField;
        
        private string descricaoProjetoField;
        
        private string descricaoSolicitacaoField;
        
        private System.Nullable<double> duracaoField;
        
        private bool duracaoFieldSpecified;
        
        private System.Nullable<int> idApontamentoField;
        
        private bool idApontamentoFieldSpecified;
        
        private System.Nullable<int> idAreaField;
        
        private bool idAreaFieldSpecified;
        
        private System.Nullable<int> idAreaExternoField;
        
        private bool idAreaExternoFieldSpecified;
        
        private System.Nullable<int> idAtividadeField;
        
        private bool idAtividadeFieldSpecified;
        
        private System.Nullable<int> idAtividadeExternoField;
        
        private bool idAtividadeExternoFieldSpecified;
        
        private System.Nullable<int> idProgramaField;
        
        private bool idProgramaFieldSpecified;
        
        private System.Nullable<int> idProgramaExternoField;
        
        private bool idProgramaExternoFieldSpecified;
        
        private System.Nullable<int> idProjetoField;
        
        private bool idProjetoFieldSpecified;
        
        private System.Nullable<int> idRubricaField;
        
        private bool idRubricaFieldSpecified;
        
        private System.Nullable<int> idRubricaExternoField;
        
        private bool idRubricaExternoFieldSpecified;
        
        private System.Nullable<int> idTarefaField;
        
        private bool idTarefaFieldSpecified;
        
        private System.Nullable<int> idTarefaExternoField;
        
        private bool idTarefaExternoFieldSpecified;
        
        private System.Nullable<int> idTicketField;
        
        private bool idTicketFieldSpecified;
        
        private System.Nullable<int> idTicketExternoField;
        
        private bool idTicketExternoFieldSpecified;
        
        private System.Nullable<int> idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private System.Nullable<int> idUsuarioExternoField;
        
        private bool idUsuarioExternoFieldSpecified;
        
        private string statusField;
        
        private string tipoOperacaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codigoProjeto {
            get {
                return this.codigoProjetoField;
            }
            set {
                this.codigoProjetoField = value;
                this.RaisePropertyChanged("codigoProjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dataApontamento {
            get {
                return this.dataApontamentoField;
            }
            set {
                this.dataApontamentoField = value;
                this.RaisePropertyChanged("dataApontamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string descricaoAtividade {
            get {
                return this.descricaoAtividadeField;
            }
            set {
                this.descricaoAtividadeField = value;
                this.RaisePropertyChanged("descricaoAtividade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string descricaoPrograma {
            get {
                return this.descricaoProgramaField;
            }
            set {
                this.descricaoProgramaField = value;
                this.RaisePropertyChanged("descricaoPrograma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string descricaoProjeto {
            get {
                return this.descricaoProjetoField;
            }
            set {
                this.descricaoProjetoField = value;
                this.RaisePropertyChanged("descricaoProjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string descricaoSolicitacao {
            get {
                return this.descricaoSolicitacaoField;
            }
            set {
                this.descricaoSolicitacaoField = value;
                this.RaisePropertyChanged("descricaoSolicitacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<double> duracao {
            get {
                return this.duracaoField;
            }
            set {
                this.duracaoField = value;
                this.RaisePropertyChanged("duracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool duracaoSpecified {
            get {
                return this.duracaoFieldSpecified;
            }
            set {
                this.duracaoFieldSpecified = value;
                this.RaisePropertyChanged("duracaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> idApontamento {
            get {
                return this.idApontamentoField;
            }
            set {
                this.idApontamentoField = value;
                this.RaisePropertyChanged("idApontamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idApontamentoSpecified {
            get {
                return this.idApontamentoFieldSpecified;
            }
            set {
                this.idApontamentoFieldSpecified = value;
                this.RaisePropertyChanged("idApontamentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> idArea {
            get {
                return this.idAreaField;
            }
            set {
                this.idAreaField = value;
                this.RaisePropertyChanged("idArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAreaSpecified {
            get {
                return this.idAreaFieldSpecified;
            }
            set {
                this.idAreaFieldSpecified = value;
                this.RaisePropertyChanged("idAreaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> idAreaExterno {
            get {
                return this.idAreaExternoField;
            }
            set {
                this.idAreaExternoField = value;
                this.RaisePropertyChanged("idAreaExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAreaExternoSpecified {
            get {
                return this.idAreaExternoFieldSpecified;
            }
            set {
                this.idAreaExternoFieldSpecified = value;
                this.RaisePropertyChanged("idAreaExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> idAtividade {
            get {
                return this.idAtividadeField;
            }
            set {
                this.idAtividadeField = value;
                this.RaisePropertyChanged("idAtividade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAtividadeSpecified {
            get {
                return this.idAtividadeFieldSpecified;
            }
            set {
                this.idAtividadeFieldSpecified = value;
                this.RaisePropertyChanged("idAtividadeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> idAtividadeExterno {
            get {
                return this.idAtividadeExternoField;
            }
            set {
                this.idAtividadeExternoField = value;
                this.RaisePropertyChanged("idAtividadeExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAtividadeExternoSpecified {
            get {
                return this.idAtividadeExternoFieldSpecified;
            }
            set {
                this.idAtividadeExternoFieldSpecified = value;
                this.RaisePropertyChanged("idAtividadeExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> idPrograma {
            get {
                return this.idProgramaField;
            }
            set {
                this.idProgramaField = value;
                this.RaisePropertyChanged("idPrograma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProgramaSpecified {
            get {
                return this.idProgramaFieldSpecified;
            }
            set {
                this.idProgramaFieldSpecified = value;
                this.RaisePropertyChanged("idProgramaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> idProgramaExterno {
            get {
                return this.idProgramaExternoField;
            }
            set {
                this.idProgramaExternoField = value;
                this.RaisePropertyChanged("idProgramaExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProgramaExternoSpecified {
            get {
                return this.idProgramaExternoFieldSpecified;
            }
            set {
                this.idProgramaExternoFieldSpecified = value;
                this.RaisePropertyChanged("idProgramaExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<int> idProjeto {
            get {
                return this.idProjetoField;
            }
            set {
                this.idProjetoField = value;
                this.RaisePropertyChanged("idProjeto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProjetoSpecified {
            get {
                return this.idProjetoFieldSpecified;
            }
            set {
                this.idProjetoFieldSpecified = value;
                this.RaisePropertyChanged("idProjetoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<int> idRubrica {
            get {
                return this.idRubricaField;
            }
            set {
                this.idRubricaField = value;
                this.RaisePropertyChanged("idRubrica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRubricaSpecified {
            get {
                return this.idRubricaFieldSpecified;
            }
            set {
                this.idRubricaFieldSpecified = value;
                this.RaisePropertyChanged("idRubricaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> idRubricaExterno {
            get {
                return this.idRubricaExternoField;
            }
            set {
                this.idRubricaExternoField = value;
                this.RaisePropertyChanged("idRubricaExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRubricaExternoSpecified {
            get {
                return this.idRubricaExternoFieldSpecified;
            }
            set {
                this.idRubricaExternoFieldSpecified = value;
                this.RaisePropertyChanged("idRubricaExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<int> idTarefa {
            get {
                return this.idTarefaField;
            }
            set {
                this.idTarefaField = value;
                this.RaisePropertyChanged("idTarefa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTarefaSpecified {
            get {
                return this.idTarefaFieldSpecified;
            }
            set {
                this.idTarefaFieldSpecified = value;
                this.RaisePropertyChanged("idTarefaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<int> idTarefaExterno {
            get {
                return this.idTarefaExternoField;
            }
            set {
                this.idTarefaExternoField = value;
                this.RaisePropertyChanged("idTarefaExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTarefaExternoSpecified {
            get {
                return this.idTarefaExternoFieldSpecified;
            }
            set {
                this.idTarefaExternoFieldSpecified = value;
                this.RaisePropertyChanged("idTarefaExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<int> idTicket {
            get {
                return this.idTicketField;
            }
            set {
                this.idTicketField = value;
                this.RaisePropertyChanged("idTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTicketSpecified {
            get {
                return this.idTicketFieldSpecified;
            }
            set {
                this.idTicketFieldSpecified = value;
                this.RaisePropertyChanged("idTicketSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> idTicketExterno {
            get {
                return this.idTicketExternoField;
            }
            set {
                this.idTicketExternoField = value;
                this.RaisePropertyChanged("idTicketExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTicketExternoSpecified {
            get {
                return this.idTicketExternoFieldSpecified;
            }
            set {
                this.idTicketExternoFieldSpecified = value;
                this.RaisePropertyChanged("idTicketExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<int> idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<int> idUsuarioExterno {
            get {
                return this.idUsuarioExternoField;
            }
            set {
                this.idUsuarioExternoField = value;
                this.RaisePropertyChanged("idUsuarioExterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioExternoSpecified {
            get {
                return this.idUsuarioExternoFieldSpecified;
            }
            set {
                this.idUsuarioExternoFieldSpecified = value;
                this.RaisePropertyChanged("idUsuarioExternoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string tipoOperacao {
            get {
                return this.tipoOperacaoField;
            }
            set {
                this.tipoOperacaoField = value;
                this.RaisePropertyChanged("tipoOperacao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br/xsd")]
    public partial class Resposta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private string msgField;
        
        private System.Nullable<bool> sucessoField;
        
        private bool sucessoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sucessoSpecified {
            get {
                return this.sucessoFieldSpecified;
            }
            set {
                this.sucessoFieldSpecified = value;
                this.RaisePropertyChanged("sucessoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generics.channel2.jexperts.com.br/xsd")]
    public partial class ResultadoOperacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> idField;
        
        private bool idFieldSpecified;
        
        private System.Nullable<int> idEmpresaField;
        
        private bool idEmpresaFieldSpecified;
        
        private object logField;
        
        private string mensagemField;
        
        private object objectField;
        
        private bool realizadaField;
        
        private bool realizadaFieldSpecified;
        
        private string tipoMensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                this.idEmpresaField = value;
                this.RaisePropertyChanged("idEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idEmpresaSpecified {
            get {
                return this.idEmpresaFieldSpecified;
            }
            set {
                this.idEmpresaFieldSpecified = value;
                this.RaisePropertyChanged("idEmpresaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public object log {
            get {
                return this.logField;
            }
            set {
                this.logField = value;
                this.RaisePropertyChanged("log");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public object @object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
                this.RaisePropertyChanged("object");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool realizada {
            get {
                return this.realizadaField;
            }
            set {
                this.realizadaField = value;
                this.RaisePropertyChanged("realizada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool realizadaSpecified {
            get {
                return this.realizadaFieldSpecified;
            }
            set {
                this.realizadaFieldSpecified = value;
                this.RaisePropertyChanged("realizadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string tipoMensagem {
            get {
                return this.tipoMensagemField;
            }
            set {
                this.tipoMensagemField = value;
                this.RaisePropertyChanged("tipoMensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaApontamentosPendentes", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listaApontamentosPendentesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipoOperacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        public int idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=2)]
        public int idArea;
        
        public listaApontamentosPendentesRequest() {
        }
        
        public listaApontamentosPendentesRequest(string tipoOperacao, int idUsuario, int idArea) {
            this.tipoOperacao = tipoOperacao;
            this.idUsuario = idUsuario;
            this.idArea = idArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaApontamentosPendentesResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class listaApontamentosPendentesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Xerife.Business.ChannelApontamentoWebService.ApontamentoPendente[] @return;
        
        public listaApontamentosPendentesResponse() {
        }
        
        public listaApontamentosPendentesResponse(Xerife.Business.ChannelApontamentoWebService.ApontamentoPendente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarApontamentoOperacao", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class registrarApontamentoOperacaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idOperacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idTicket;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idRubrica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idTipoAtividade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idTarefaSolicitacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idPassoWorkflow;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valorHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataApontamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string colaborador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricao;
        
        public registrarApontamentoOperacaoRequest() {
        }
        
        public registrarApontamentoOperacaoRequest(string idOperacao, string idTicket, string idRubrica, string idCliente, string idTipoAtividade, string idTarefaSolicitacao, string idPassoWorkflow, string valorHora, string dataApontamento, string colaborador, string descricao) {
            this.idOperacao = idOperacao;
            this.idTicket = idTicket;
            this.idRubrica = idRubrica;
            this.idCliente = idCliente;
            this.idTipoAtividade = idTipoAtividade;
            this.idTarefaSolicitacao = idTarefaSolicitacao;
            this.idPassoWorkflow = idPassoWorkflow;
            this.valorHora = valorHora;
            this.dataApontamento = dataApontamento;
            this.colaborador = colaborador;
            this.descricao = descricao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarApontamentoOperacaoResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class registrarApontamentoOperacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao @return;
        
        public registrarApontamentoOperacaoResponse() {
        }
        
        public registrarApontamentoOperacaoResponse(Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarApontamento", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class registrarApontamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        public int idAtividade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valorHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> dataApontamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string colaborador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricao;
        
        public registrarApontamentoRequest() {
        }
        
        public registrarApontamentoRequest(int idAtividade, string valorHora, System.Nullable<System.DateTime> dataApontamento, string colaborador, string descricao) {
            this.idAtividade = idAtividade;
            this.valorHora = valorHora;
            this.dataApontamento = dataApontamento;
            this.colaborador = colaborador;
            this.descricao = descricao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarApontamentoResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class registrarApontamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao @return;
        
        public registrarApontamentoResponse() {
        }
        
        public registrarApontamentoResponse(Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarApontamentoAvulso", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class registrarApontamentoAvulsoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idTipoOperacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idTipoAtividade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valorHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataApontamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string colaborador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricao;
        
        public registrarApontamentoAvulsoRequest() {
        }
        
        public registrarApontamentoAvulsoRequest(string idCliente, string idTipoOperacao, string idTipoAtividade, string valorHora, string dataApontamento, string colaborador, string descricao) {
            this.idCliente = idCliente;
            this.idTipoOperacao = idTipoOperacao;
            this.idTipoAtividade = idTipoAtividade;
            this.valorHora = valorHora;
            this.dataApontamento = dataApontamento;
            this.colaborador = colaborador;
            this.descricao = descricao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarApontamentoAvulsoResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class registrarApontamentoAvulsoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao @return;
        
        public registrarApontamentoAvulsoResponse() {
        }
        
        public registrarApontamentoAvulsoResponse(Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processeApontamentosRealizados", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class processeApontamentosRealizadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("listaApontamentos")]
        public int[] listaApontamentos;
        
        public processeApontamentosRealizadosRequest() {
        }
        
        public processeApontamentosRealizadosRequest(int[] listaApontamentos) {
            this.listaApontamentos = listaApontamentos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processeApontamentosRealizadosResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class processeApontamentosRealizadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Xerife.Business.ChannelApontamentoWebService.Resposta @return;
        
        public processeApontamentosRealizadosResponse() {
        }
        
        public processeApontamentosRealizadosResponse(Xerife.Business.ChannelApontamentoWebService.Resposta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarApontamentoProjeto", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class registrarApontamentoProjetoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idProjeto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idAtividade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idTipoAtividade;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string idTarefa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valorHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dataApontamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string colaborador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descricao;
        
        public registrarApontamentoProjetoRequest() {
        }
        
        public registrarApontamentoProjetoRequest(string idProjeto, string idAtividade, string idTipoAtividade, string idTarefa, string valorHora, string dataApontamento, string colaborador, string descricao) {
            this.idProjeto = idProjeto;
            this.idAtividade = idAtividade;
            this.idTipoAtividade = idTipoAtividade;
            this.idTarefa = idTarefa;
            this.valorHora = valorHora;
            this.dataApontamento = dataApontamento;
            this.colaborador = colaborador;
            this.descricao = descricao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="registrarApontamentoProjetoResponse", WrapperNamespace="http://integracao.webservices.channel2.jexperts.com.br", IsWrapped=true)]
    public partial class registrarApontamentoProjetoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://integracao.webservices.channel2.jexperts.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao @return;
        
        public registrarApontamentoProjetoResponse() {
        }
        
        public registrarApontamentoProjetoResponse(Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChannelApontamentoWebServicePortTypeChannel : Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChannelApontamentoWebServicePortTypeClient : System.ServiceModel.ClientBase<Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType>, Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType {
        
        public ChannelApontamentoWebServicePortTypeClient() {
        }
        
        public ChannelApontamentoWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChannelApontamentoWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelApontamentoWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChannelApontamentoWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesResponse Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.listaApontamentosPendentes(Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesRequest request) {
            return base.Channel.listaApontamentosPendentes(request);
        }
        
        public Xerife.Business.ChannelApontamentoWebService.ApontamentoPendente[] listaApontamentosPendentes(string tipoOperacao, int idUsuario, int idArea) {
            Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesRequest inValue = new Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesRequest();
            inValue.tipoOperacao = tipoOperacao;
            inValue.idUsuario = idUsuario;
            inValue.idArea = idArea;
            Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesResponse retVal = ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).listaApontamentosPendentes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesResponse> Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.listaApontamentosPendentesAsync(Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesRequest request) {
            return base.Channel.listaApontamentosPendentesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesResponse> listaApontamentosPendentesAsync(string tipoOperacao, int idUsuario, int idArea) {
            Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesRequest inValue = new Xerife.Business.ChannelApontamentoWebService.listaApontamentosPendentesRequest();
            inValue.tipoOperacao = tipoOperacao;
            inValue.idUsuario = idUsuario;
            inValue.idArea = idArea;
            return ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).listaApontamentosPendentesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoResponse Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.registrarApontamentoOperacao(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoRequest request) {
            return base.Channel.registrarApontamentoOperacao(request);
        }
        
        public Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao registrarApontamentoOperacao(string idOperacao, string idTicket, string idRubrica, string idCliente, string idTipoAtividade, string idTarefaSolicitacao, string idPassoWorkflow, string valorHora, string dataApontamento, string colaborador, string descricao) {
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoRequest inValue = new Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoRequest();
            inValue.idOperacao = idOperacao;
            inValue.idTicket = idTicket;
            inValue.idRubrica = idRubrica;
            inValue.idCliente = idCliente;
            inValue.idTipoAtividade = idTipoAtividade;
            inValue.idTarefaSolicitacao = idTarefaSolicitacao;
            inValue.idPassoWorkflow = idPassoWorkflow;
            inValue.valorHora = valorHora;
            inValue.dataApontamento = dataApontamento;
            inValue.colaborador = colaborador;
            inValue.descricao = descricao;
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoResponse retVal = ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).registrarApontamentoOperacao(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoResponse> Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.registrarApontamentoOperacaoAsync(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoRequest request) {
            return base.Channel.registrarApontamentoOperacaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoResponse> registrarApontamentoOperacaoAsync(string idOperacao, string idTicket, string idRubrica, string idCliente, string idTipoAtividade, string idTarefaSolicitacao, string idPassoWorkflow, string valorHora, string dataApontamento, string colaborador, string descricao) {
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoRequest inValue = new Xerife.Business.ChannelApontamentoWebService.registrarApontamentoOperacaoRequest();
            inValue.idOperacao = idOperacao;
            inValue.idTicket = idTicket;
            inValue.idRubrica = idRubrica;
            inValue.idCliente = idCliente;
            inValue.idTipoAtividade = idTipoAtividade;
            inValue.idTarefaSolicitacao = idTarefaSolicitacao;
            inValue.idPassoWorkflow = idPassoWorkflow;
            inValue.valorHora = valorHora;
            inValue.dataApontamento = dataApontamento;
            inValue.colaborador = colaborador;
            inValue.descricao = descricao;
            return ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).registrarApontamentoOperacaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelApontamentoWebService.registrarApontamentoResponse Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.registrarApontamento(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoRequest request) {
            return base.Channel.registrarApontamento(request);
        }
        
        public Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao registrarApontamento(int idAtividade, string valorHora, System.Nullable<System.DateTime> dataApontamento, string colaborador, string descricao) {
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoRequest inValue = new Xerife.Business.ChannelApontamentoWebService.registrarApontamentoRequest();
            inValue.idAtividade = idAtividade;
            inValue.valorHora = valorHora;
            inValue.dataApontamento = dataApontamento;
            inValue.colaborador = colaborador;
            inValue.descricao = descricao;
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoResponse retVal = ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).registrarApontamento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoResponse> Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.registrarApontamentoAsync(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoRequest request) {
            return base.Channel.registrarApontamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoResponse> registrarApontamentoAsync(int idAtividade, string valorHora, System.Nullable<System.DateTime> dataApontamento, string colaborador, string descricao) {
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoRequest inValue = new Xerife.Business.ChannelApontamentoWebService.registrarApontamentoRequest();
            inValue.idAtividade = idAtividade;
            inValue.valorHora = valorHora;
            inValue.dataApontamento = dataApontamento;
            inValue.colaborador = colaborador;
            inValue.descricao = descricao;
            return ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).registrarApontamentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoResponse Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.registrarApontamentoAvulso(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoRequest request) {
            return base.Channel.registrarApontamentoAvulso(request);
        }
        
        public Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao registrarApontamentoAvulso(string idCliente, string idTipoOperacao, string idTipoAtividade, string valorHora, string dataApontamento, string colaborador, string descricao) {
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoRequest inValue = new Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoRequest();
            inValue.idCliente = idCliente;
            inValue.idTipoOperacao = idTipoOperacao;
            inValue.idTipoAtividade = idTipoAtividade;
            inValue.valorHora = valorHora;
            inValue.dataApontamento = dataApontamento;
            inValue.colaborador = colaborador;
            inValue.descricao = descricao;
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoResponse retVal = ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).registrarApontamentoAvulso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoResponse> Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.registrarApontamentoAvulsoAsync(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoRequest request) {
            return base.Channel.registrarApontamentoAvulsoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoResponse> registrarApontamentoAvulsoAsync(string idCliente, string idTipoOperacao, string idTipoAtividade, string valorHora, string dataApontamento, string colaborador, string descricao) {
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoRequest inValue = new Xerife.Business.ChannelApontamentoWebService.registrarApontamentoAvulsoRequest();
            inValue.idCliente = idCliente;
            inValue.idTipoOperacao = idTipoOperacao;
            inValue.idTipoAtividade = idTipoAtividade;
            inValue.valorHora = valorHora;
            inValue.dataApontamento = dataApontamento;
            inValue.colaborador = colaborador;
            inValue.descricao = descricao;
            return ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).registrarApontamentoAvulsoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosResponse Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.processeApontamentosRealizados(Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosRequest request) {
            return base.Channel.processeApontamentosRealizados(request);
        }
        
        public Xerife.Business.ChannelApontamentoWebService.Resposta processeApontamentosRealizados(int[] listaApontamentos) {
            Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosRequest inValue = new Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosRequest();
            inValue.listaApontamentos = listaApontamentos;
            Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosResponse retVal = ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).processeApontamentosRealizados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosResponse> Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.processeApontamentosRealizadosAsync(Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosRequest request) {
            return base.Channel.processeApontamentosRealizadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosResponse> processeApontamentosRealizadosAsync(int[] listaApontamentos) {
            Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosRequest inValue = new Xerife.Business.ChannelApontamentoWebService.processeApontamentosRealizadosRequest();
            inValue.listaApontamentos = listaApontamentos;
            return ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).processeApontamentosRealizadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoResponse Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.registrarApontamentoProjeto(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoRequest request) {
            return base.Channel.registrarApontamentoProjeto(request);
        }
        
        public Xerife.Business.ChannelApontamentoWebService.ResultadoOperacao registrarApontamentoProjeto(string idProjeto, string idAtividade, string idTipoAtividade, string idTarefa, string valorHora, string dataApontamento, string colaborador, string descricao) {
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoRequest inValue = new Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoRequest();
            inValue.idProjeto = idProjeto;
            inValue.idAtividade = idAtividade;
            inValue.idTipoAtividade = idTipoAtividade;
            inValue.idTarefa = idTarefa;
            inValue.valorHora = valorHora;
            inValue.dataApontamento = dataApontamento;
            inValue.colaborador = colaborador;
            inValue.descricao = descricao;
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoResponse retVal = ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).registrarApontamentoProjeto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoResponse> Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType.registrarApontamentoProjetoAsync(Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoRequest request) {
            return base.Channel.registrarApontamentoProjetoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoResponse> registrarApontamentoProjetoAsync(string idProjeto, string idAtividade, string idTipoAtividade, string idTarefa, string valorHora, string dataApontamento, string colaborador, string descricao) {
            Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoRequest inValue = new Xerife.Business.ChannelApontamentoWebService.registrarApontamentoProjetoRequest();
            inValue.idProjeto = idProjeto;
            inValue.idAtividade = idAtividade;
            inValue.idTipoAtividade = idTipoAtividade;
            inValue.idTarefa = idTarefa;
            inValue.valorHora = valorHora;
            inValue.dataApontamento = dataApontamento;
            inValue.colaborador = colaborador;
            inValue.descricao = descricao;
            return ((Xerife.Business.ChannelApontamentoWebService.ChannelApontamentoWebServicePortType)(this)).registrarApontamentoProjetoAsync(inValue);
        }
    }
}
